package de.hahn.blog.sqlinclause.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 23 07:23:24 CEST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesOfDepartmentsQueryImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesOfDepartmentsQueryImpl() {
    }

    /**
     * Returns the bind variable value for pListOfValues.
     * @return bind variable value for pListOfValues
     */
    public String getpListOfValues() {
        return (String) getNamedWhereClauseParam("pListOfValues");
    }

    /**
     * Sets <code>value</code> for bind variable pListOfValues.
     * @param value value to bind as pListOfValues
     */
    public void setpListOfValues(String value) {
        setNamedWhereClauseParam("pListOfValues", value);
    }
}

